"""
Daily ingestion pipeline – pseudocode / implementation plan.

OVERVIEW
========
This function runs once every 24 hours (scheduled by APScheduler in main.py).
It syncs our database with ClinicalTrials.gov for a list of search terms.

EXISTING CODE USED
==================
- app.services.ctgov.study_index.iter_study_index_rows(search_term, ...)
    → yields (nct_id, last_update_posted_date) for every study matching a term.
- app.services.ctgov.study_detail.get_trial_data(nct_id)
    → fetches full study JSON from ClinicalTrials.gov API v2.

DATABASE TABLES (see app.db.models)
====================================
- ClinicalTrial      → relevant trials (status: PENDING_REVIEW / APPROVED / REJECTED)
- IrrelevantTrial    → trials previously marked irrelevant by AI (kept for dedup)

Both share the same field set via ClinicalTrialBase (nct_id is primary key).

ClinicalTrials.gov API v2 FIELD MAPPING
========================================
The single-study endpoint GET /api/v2/studies/{nct_id} returns nested JSON.
We map it to our flat model like this:

    API path                                                    → DB column
    ─────────────────────────────────────────────────────────    ──────────────────────────────
    protocolSection.identificationModule.nctId                  → nct_id
    protocolSection.identificationModule.briefTitle             → brief_title
    protocolSection.descriptionModule.briefSummary              → brief_summary
    protocolSection.statusModule.overallStatus                  → overall_status
    protocolSection.designModule.phases                         → phase  (joined as string)
    protocolSection.designModule.studyType                      → study_type
    protocolSection.contactsLocationsModule.locations[].country → location_country  (deduplicated, comma-joined)
    protocolSection.contactsLocationsModule.locations[].city    → location_city     (deduplicated, comma-joined)
    protocolSection.eligibilityModule.minimumAge                → minimum_age
    protocolSection.eligibilityModule.maximumAge                → maximum_age
    protocolSection.contactsLocationsModule.centralContacts[0]  → central_contact_name / phone / email
    protocolSection.eligibilityModule.eligibilityCriteria       → eligibility_criteria
    protocolSection.armsInterventionsModule.interventions       → intervention_description (formatted)
    protocolSection.statusModule.lastUpdatePostDateStruct.date  → last_update_post_date

    The "custom_*" columns (custom_brief_summary, custom_eligibility_criteria, etc.)
    are NOT fetched from the API — they are generated by an AI summarisation step (see below).

AI SERVICES (to be implemented by another developer)
=====================================================
- ai_generate_summaries(trial_json) → dict of custom_* fields
    Takes the raw API data and produces patient-friendly text for:
      custom_brief_title, custom_brief_summary, custom_overall_status,
      custom_phase, custom_study_type, custom_eligibility_criteria,
      custom_intervention_description, key_information, etc.

- ai_classify_relevance(trial_json) → bool
    Decides whether the trial is relevant to our audience (osteosarcoma patients).
    Returns True → store in ClinicalTrial (PENDING_REVIEW).
    Returns False → store in IrrelevantTrial with a reason.
"""

import asyncio
from typing import List

from sqlalchemy import select

from app.db.database import SessionLocal
from app.db.models import ClinicalTrial, IrrelevantTrial
from app.services.ctgov import iter_study_index_rows


async def run_daily_ingestion(
    search_terms: List[str] | None = None,
):
    if search_terms is None:
        search_terms = ["osteosarcoma"]

    # ──────────────────────────────────────────────────────────
    # STEP 1 — Collect NCT IDs + last-update dates for each term
    # ──────────────────────────────────────────────────────────
    all_candidates: dict[str, str] = {}

    for term in search_terms:
        rows = await asyncio.to_thread(
            lambda t=term: list(iter_study_index_rows(search_term=t))
        )
        for nct_id, last_update in rows:
            all_candidates[nct_id] = last_update

    # ──────────────────────────────────────────────────────────
    # STEP 2 — Classify each NCT ID against our database
    # ──────────────────────────────────────────────────────────
    new_trials: list[str] = []
    updated_trials: list[str] = []
    rejected_hits: list[tuple[str, str, str | None]] = []

    candidate_ids = list(all_candidates.keys())

    async with SessionLocal() as db:
        result = await db.execute(
            select(ClinicalTrial.nct_id, ClinicalTrial.last_update_post_date)
            .where(ClinicalTrial.nct_id.in_(candidate_ids))
        )
        existing_map = {row.nct_id: row.last_update_post_date for row in result}

        result = await db.execute(
            select(IrrelevantTrial.nct_id, IrrelevantTrial.last_update_post_date)
            .where(IrrelevantTrial.nct_id.in_(candidate_ids))
        )
        rejected_map = {row.nct_id: row.last_update_post_date for row in result}

    for nct_id, api_date in all_candidates.items():
        if nct_id in existing_map:
            db_date = existing_map[nct_id] or ""
            if db_date != api_date:
                updated_trials.append(nct_id)
            continue

        if nct_id in rejected_map:
            rejected_hits.append((nct_id, api_date, rejected_map[nct_id]))
            continue

        new_trials.append(nct_id)

    # ──────────────────────────────────────────────────────────
    # STEP 3 — Fetch full study data for trials that need processing
    # Uses: ClinicalTrials.gov API v2  GET /api/v2/studies/{nct_id}
    # (see app.services.ctgov.study_detail for reference implementation)
    # ──────────────────────────────────────────────────────────
    #
    #   trials_to_process = new_trials + updated_trials
    #
    #   for nct_id in trials_to_process:
    #       raw_json = fetch_full_study(nct_id)
    #           → GET https://clinicaltrials.gov/api/v2/studies/{nct_id}
    #           → returns nested JSON with protocolSection.*
    #
    #       trial_data = map_api_to_model(raw_json)
    #           → Extracts fields into a flat dict matching ClinicalTrialBase columns:
    #             {
    #               "nct_id":                   "NCT04132895",
    #               "brief_title":              "Official Title of the Study",
    #               "brief_summary":            "The official, technical summary...",
    #               "overall_status":           "Recruiting",
    #               "phase":                    "Phase 2",
    #               "study_type":               "Interventional",
    #               "location_country":         "United States, Canada",
    #               "location_city":            "Houston, Toronto",
    #               "minimum_age":              "18 Years",
    #               "maximum_age":              "65 Years",
    #               "central_contact_name":     "Dr. Smith",
    #               "central_contact_phone":    "555-123-4567",
    #               "central_contact_email":    "contact@trial.com",
    #               "eligibility_criteria":     "Official inclusion and exclusion criteria text...",
    #               "intervention_description": "Official description of the drug...",
    #               "last_update_post_date":    "2024-01-01",
    #
    #               # custom_* fields are NULL at this point — filled by AI in step 4
    #               "custom_brief_title":       None,
    #               "custom_brief_summary":     None,
    #               ...
    #             }

    # ──────────────────────────────────────────────────────────
    # STEP 4 — AI summarisation (another developer's responsibility)
    # Generates patient-friendly "custom_*" fields from the raw data.
    # ──────────────────────────────────────────────────────────
    #
    #       custom_fields = await ai_generate_summaries(trial_data)
    #           → Returns dict like:
    #             {
    #               "custom_brief_title":                "Patient-Friendly Title",
    #               "custom_brief_summary":              "Easy-to-read summary of the trial's aim.",
    #               "custom_overall_status":             "Recruiting now",
    #               "custom_study_type":                 "New treatments",
    #               "custom_eligibility_criteria":       "Summarized inclusion/exclusion criteria.",
    #               "custom_intervention_description":   "Patient-friendly description of the treatment",
    #               "key_information":                   "Bulleted list of key info points.",
    #               ...
    #             }
    #
    #       trial_data.update(custom_fields)

    # ──────────────────────────────────────────────────────────
    # STEP 5 — AI relevance classification (another developer's responsibility)
    # Decides if this trial belongs in ClinicalTrial or IrrelevantTrial.
    # ──────────────────────────────────────────────────────────
    #
    #       is_relevant = await ai_classify_relevance(trial_data)
    #
    #       if is_relevant:
    #           upsert into ClinicalTrial with status = PENDING_REVIEW
    #       else:
    #           upsert into IrrelevantTrial with irrelevance_reason from AI

    # ──────────────────────────────────────────────────────────
    # STEP 6 — Handle rejected-table hits (TBD – policy not finalised)
    # ──────────────────────────────────────────────────────────
    #
    #   for nct_id, api_date, stored_date in rejected_hits:
    #       if api_date != stored_date:
    #           # Trial was updated since we last rejected it → re-evaluate?
    #           # TBD: re-run steps 3-5 for this NCT
    #           pass
    #       else:
    #           # No change since rejection → skip
    #           pass

    # ──────────────────────────────────────────────────────────
    # STEP 7 — Log summary
    # ──────────────────────────────────────────────────────────
    #
    #   print(f"Ingestion complete.")
    #   print(f"  Search terms:   {search_terms}")
    #   print(f"  Total from API: {len(all_candidates)}")
    #   print(f"  New trials:     {len(new_trials)}")
    #   print(f"  Updated trials: {len(updated_trials)}")
    #   print(f"  Rejected hits:  {len(rejected_hits)}")

    raise NotImplementedError(
        "run_daily_ingestion is not yet implemented. Implement the ingestion "
        "pipeline or disable the scheduled job and related endpoints before "
        "enabling this in production."
    )


if __name__ == "__main__":
    asyncio.run(run_daily_ingestion())
