name: Bug report
description: Report a reproducible problem in ACTE.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug. Please include enough detail to reproduce.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the system is affected?
      options:
        - Backend API (FastAPI)
        - Data ingestion pipeline
        - Database / migrations (Alembic)
        - Frontend (Vite/React)
        - Deployment / Docker
        - Documentation
        - Not sure
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: "When I..., I expected..., but..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide clear steps so we can reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste relevant logs (redact secrets). If you can, include stack traces.
      render: text
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Commit / version
      description: Git commit SHA, tag, or "main".
      placeholder: "e.g., 1a2b3c4 or main"
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, Node version, Docker version, etc.
      placeholder: |
        - OS:
        - Python:
        - Node:
        - Docker:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues to avoid duplicates.
          required: true
        - label: I removed or redacted any secrets (API keys, tokens, PHI/PII).
          required: true
